apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-local
  labels:
    environment: local
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage

