apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-local
  labels:
    environment: "local"
spec:
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/opo/University/Article/monitoring/monitoring/grafana"
    type: DirectoryOrCreate
